brainpy/BrainPy

- README.rst
- brainpy/__init__.py
- brainpy/core_system/base.py
- develop/conda-recipe/meta.yaml
- docs/apis/changelog.rst
- requirements.txt
- setup.py
> Version 0.2.4

- brainpy/backend/drivers/numba_cpu.py
- brainpy/backend/drivers/numba_cuda.py
- brainpy/simulation/connectivity/base.py
- examples/numba_cuda/AMPA_synapse.py
- examples/numba_cuda/COBA.py
- examples/numba_cuda/HH_model.py
- examples/numba_cuda/LIF_model.py
- tests/backend/drivers/test_numba_cuda_on_func_of_monitor.py
- Fix bugs in connectivity 
- Fix bugs of inputs_format
- Support monitor on CPU in Numba CUDA backend
- Add COBA EI net example for Numba CUDA backend
-  Update Numba CUDA examples
> Improve for Numba CUDA backend

- brainpy/analysis/lowdim/lowdim_analyzer.py
- brainpy/analysis/lowdim/lowdim_bifurcation.py
- brainpy/analysis/lowdim/lowdim_phase_plane.py
- setup.py
> fix matplotlib dependency on "brainpy.analysis" module

- .github/workflows/Sync_branches.yml
A new GitHub workflow: when a PR merges to master, this workflow will automatically merge master branch to brainpy-2.0 branch for syncronizatioin.
> Sync master to brainpy-2.x branch

- brainpy/math/operators.py
- extensions/brainpylib/__init__.py
- extensions/brainpylib/custom_op/cpu.py
- extensions/brainpylib/custom_op/gpu.py
- extensions/brainpylib/custom_op/regis_op.py
Fix register_op structure & Compatible with the future update of GPU operators.
> Fix: modify `register_op` and brainpy.math interface

- .github/workflows/generate_changelog.yml
Auto-generate changelog and auto-categorization commit based on commit information.
> feat: add generate_changelog

- brainpy/nn/nodes/ANN/__init__.py
- brainpy/nn/nodes/ANN/batch_norm.py
- brainpy/nn/nodes/ANN/tests/test_batchnorm.py
- brainpy/nn/nodes/base/io.py
- brainpy/nn/nodes/base/ops.py
add the batch normalization node
some modifications in other related files
> feat: add the batch normalization node

- brainpy/nn/nodes/ANN/batch_norm.py
- brainpy/nn/nodes/ANN/tests/test_batchnorm.py
update the API and test for batch normalization.
> feat: update the API and test for batch normalization 

- extensions/brainpylib/__init__.py
- extensions/changelog.rst
- extensions/setup.py
- extensions/setup_cuda.py
- extensions/setup_mac.py
fix: add dependencies and update version
> fix: add dependencies and update version

- docs/quickstart/installation.rst
docs: add m1 warning about ``jaxlib`` installation.
> docs: add m1 warning

- README.md
- brainpy/connect/random_conn.py
- brainpy/connect/regular_conn.py
- brainpy/dyn/neurons/biological_models.py
- brainpy/dyn/neurons/fractional_models.py
- brainpy/dyn/neurons/input_models.py
- brainpy/dyn/neurons/noise_models.py
- brainpy/dyn/neurons/rate_models.py
- brainpy/dyn/neurons/reduced_models.py
- brainpy/dyn/utils.py
- brainpy/initialize/generic.py
- brainpy/integrators/base.py
- brainpy/integrators/dde/base.py
- brainpy/integrators/dde/explicit_rk.py
- brainpy/integrators/fde/Caputo.py
- brainpy/integrators/fde/GL.py
- brainpy/integrators/ode/adaptive_rk.py
- brainpy/integrators/ode/base.py
- brainpy/integrators/ode/explicit_rk.py
- brainpy/integrators/ode/exponential.py
- brainpy/integrators/sde/base.py
- brainpy/math/jaxarray.py
- brainpy/nn/nodes/ANN/batch_norm.py
- brainpy/nn/nodes/ANN/tests/test_batchnorm.py
- extensions/brainpylib/__init__.py
- extensions/build_wheel_in_linux.sh
- extensions/changelog.rst
- extensions/setup.py
- extensions/setup_cuda.py
- extensions/setup_mac.py
- [update integrator apis](https://github.com/PKU-NIP-Lab/BrainPy/commit/0c65f77914703f6210bef33163da705193b9b5ff)
- [feat: interface interchange with jax and numpy](https://github.com/PKU-NIP-Lab/BrainPy/commit/7271730468de6cb286f13399c1fb78af44060598)
- [feat: standarize neuron models, making parameter able to be heterogen…](https://github.com/PKU-NIP-Lab/BrainPy/commit/f4b8b70e897f1f47a9189a07b732fa2219010b2b)
> Important updates

- .github/workflows/Sync_branches.yml
> fix: change trigger condition

- brainpy/connect/base.py
- brainpy/connect/custom_conn.py
- brainpy/connect/random_conn.py
- brainpy/connect/regular_conn.py
- docs/tutorial_toolbox/synaptic_connections.ipynb
fix: add build_conn() function and reconstruct require() function.
Documentations will be updated tonight.
> fix: add build_conn() function

- brainpy/dyn/base.py
- brainpy/dyn/synapses/abstract_models.py
- brainpy/dyn/synapses/biological_models.py
- brainpy/dyn/synapses/learning_rules.py
- brainpy/math/jaxarray.py
- [synapse models support heterogeneuos weights](https://github.com/PKU-NIP-Lab/BrainPy/commit/9406e7a3c22c6fb43f911c4e929cff1408dbeef2)
- [update "get_delay" function](https://github.com/PKU-NIP-Lab/BrainPy/commit/92fac4a6c94931c093a7db852c33be541925f2d9)
- [fix ".astype" bug](https://github.com/PKU-NIP-Lab/BrainPy/commit/a6e61fc5d5e61c69219522152d798898f97e3e95)
> synapse models support heterogeneuos weights

- brainpy/connect/custom_conn.py
> fix: np array astype

- brainpy/math/activations.py
jnp.tanh --> brainpy.math.numpy_ops.tanh
> fix a bug in math.activations.py

- brainpy/measure/correlation.py
- brainpy/measure/tests/test_correlation.py
There is a bug in cross-correlation. I've tested my modification and it should be correct.
> fix: cross-correlation bug

- requirements-doc.txt
> fix: add requirements-doc.txt

- .gitignore
- brainpy/__init__.py
- brainpy/base/base.py
- brainpy/base/collector.py
- brainpy/base/io.py
- brainpy/base/tests/test_io.py
- brainpy/tools/checking.py
- support `.hdf5`, `.npz`, `.mat`, `.pkl` file formats
> feat: fix `io` for brainpy.Base

- docs/conf.py
- requirements-doc.txt
> docs: fix mathjax problem

- brainpy/base/base.py
- brainpy/base/tests/test_collector.py
- brainpy/dyn/neurons/biological_models.py
- brainpy/visualization/base.py
- brainpy/visualization/plots.py
> update apis and tests

- brainpy/__init__.py
- brainpy/dyn/base.py
- brainpy/dyn/channels/base.py
- brainpy/dyn/tests/test_slice_view.py
- brainpy/math/controls.py
- brainpy/math/jaxarray.py
- examples/simulation/Brette_2007_COBA.py
- examples/simulation/Brette_2007_COBAHH.py
Support a view of an instance of dynamic system. For instance
```python
>>> import brainpy as bp
>>> hh = bp.neurons.HH(100)
>>> a = hh[50:]
>>> b = hh[10:30]
```
> Support `DSView`

- brainpy/__init__.py
- brainpy/initialize/generic.py
- brainpy/math/delayvars.py
- brainpy/math/tests/test_delay_vars.py
- docs/index.rst
- docs/quickstart/installation.rst
- docs/tutorial_advanced/compile_brainpylib.rst
- setup.py
- Update installation information
- Update delay API
> Update installation info and delay apis

- brainpy/math/jaxarray.py
- brainpy/math/tests/test_jaxarray.py
```python
>>> import numpy as np
>>> import brainpy.math as bm
>>> bm.random.random(3) + np.ones(1)
JaxArray([1.2022058, 1.683937 , 1.3586301], dtype=float32)
```
> operations with JaxArray and numpy ndarray do not cause errors

- brainpy/dyn/layers/__init__.py
- brainpy/dyn/layers/activate.py
- brainpy/dyn/layers/linear.py
In order to make the construction of ANN network simple and standard, add Activation and Flatten class.
````
import brainpy as bp
import brainpy.math as bm
class Network(bp.dyn.DynamicalSystem):
def __init__(self):
super(Network, self).__init__()
self.s1 = bp.Sequential(
bp.layers.Conv2D(in_channels=1, out_channels=10,
kernel_size=(3, 3), strides=(1, 1), padding="SAME"),
bp.layers.Activation(bm.relu),
bp.layers.MaxPool(2, 2, channel_axis=-1)
)
self.s2 = bp.Sequential(
bp.layers.Conv2D(
in_channels=10, out_channels=5, kernel_size=(3, 3), strides=(1, 1), padding="SAME"),
bp.layers.Activation(bm.relu),
bp.layers.linear.Flatten()
)
self.s3 = bp.Sequential(
bp.layers.Dense(5*14*14, 30),
bp.layers.Activation(bm.relu)
)
self.s4 = bp.Sequential(
bp.layers.Dense(30, 10)
)
def update(self, s, x):
x …
```
> add Activation and Flatten class

- brainpy/datasets/vision/cifar.py
> datasets::vision: add cifar dataset

- brainpy/dyn/runners.py
- brainpy/dyn/tests/test_dyn_runner.py
- brainpy/measure/correlation.py
- brainpy/running/multiprocess.py
- brainpy/train/back_propagation.py
- brainpy/train/offline.py
- brainpy/train/online.py
This PR enables us to support more general ``DSView``.
> fix #294: remove VariableView in `dyn_vars` of a runner

- brainpy/running/__init__.py
- brainpy/running/jax_multiprocessing.py
- brainpy/running/native_multiprocessing.py
- brainpy/running/pathos_multiprocessing.py
We are enabling to run multiple brainpy functions on multiple threads/devices.
> add multiprocessing functions for batch running of BrainPy functions

- brainpy/_src/math/compat_pytorch.py
- brainpy/_src/math/ndarray.py
- brainpy/_src/math/tests/test_compat_pytorch.py
Some try to support for pytorch
Added in the test_compat_pytorch.py
> Add func 'unsqueeze' and 'expand' to support for pytorch.

- brainpy/__init__.py
- brainpy/_src/dyn/base.py
- brainpy/_src/dyn/runners.py
- brainpy/_src/initialize/generic.py
- brainpy/_src/math/environment.py
- brainpy/_src/math/modes.py
- brainpy/_src/math/operators/jitconn_ops.py
- enable monitoring GPU models on CPU when setting `DSRunner(..., memory_efficient=True)`
> Enable memory-efficient ``DSRunner``

- README.md
- brainpy/_src/dyn/neurons/hh.py
- brainpy/_src/dyn/neurons/lif.py
- brainpy/_src/tests/test_brainpy_deprecations.py
- brainpy/dyn/channels.py
- brainpy/dyn/neurons.py
Update dyn.neurons docs and fix several bugs
> [dyn] Update dyn.neurons docs and fix several bugs

- brainpy/__init__.py
- brainpy/_src/delay.py
- brainpy/_src/deprecations.py
- brainpy/_src/dyn/outs/base.py
- brainpy/_src/dyn/outs/outputs.py
- brainpy/_src/dyn/projections/aligns.py
- brainpy/_src/dyn/synapses/abstract_models.py
- brainpy/_src/dynsys.py
- brainpy/_src/math/object_transform/base.py
- brainpy/_src/mixin.py
- brainpy/_src/tests/test_delay.py
- brainpy/dyn/projections.py
- examples/dynamics_simulation/COBA.py
- examples/dynamics_simulation/COBA_parallel.py
- [delay] fix delay bug when multiple entries registered
- [delay] support batching when using .at operation
- [MgBlock] fix `brainpy.dyn.MgBlock` bugs
- [projection] support `ProjAlignPre1` and `ProjAlignPre2`
> Update delays, models, and projections

- brainpy/_src/context.py
- brainpy/_src/dynsys.py
- brainpy/_src/math/object_transform/autograd.py
> Compatible with `jax=0.4.14`

- brainpy/_src/dyn/neurons/hh.py
- brainpy/_src/dyn/neurons/lif.py
> [doc] add new strings in bp._src.dyn.hh.py and bp._src.dyn.lif.py

- brainpy/_src/dyn/projections/aligns.py
- brainpy/_src/dynold/synapses/base.py
- brainpy/_src/dynsys.py
- brainpy/_src/initialize/random_inits.py
- brainpy/_src/math/modes.py
- brainpy/_src/math/object_transform/controls.py
- brainpy/_src/math/object_transform/variables.py
- brainpy/_src/mixin.py
- brainpy/_src/tests/test_mixin.py
- docs/index.rst
- [projection] support `out_prefix` for categorizing different input resources
- [reset] new style for reset states
- Training mode to batch mode.
- [doc] update doc index
- [math] Variable value automatic transformation
> Serveral updates

- brainpy/_add_deprecations.py
- brainpy/_src/dyn/others/common.py
- brainpy/_src/encoding/base.py
- brainpy/_src/encoding/stateful_encoding.py
- brainpy/_src/encoding/stateless_encoding.py
- brainpy/_src/encoding/tests/test_stateless_encoding.py
- brainpy/_src/math/compat_pytorch.py
- brainpy/_src/visualization/animation.py
- brainpy/_src/visualization/base.py
- brainpy/encoding.py
- brainpy/math/compat_pytorch.py
- upgrade ``brainpy.encoding.PoissonEncoder``
- upgrade ``brainpy.encoding.LatencyEncoder``
- upgrade ``brainpy.encoding.DiffEncoder``
> [encoding] upgrade encoding methods

- README.md
- docs/index.rst
[docs] update README and installation
> [docs] update README and installation

- brainpy/_src/math/environment.py
- brainpy/_src/math/scales.py
Rename the parameter name to `membrane_scaling` and fix some small bugs.
> Fix bugs in membrane scaling

- brainpy/_src/math/op_register/base.py
- brainpy/_src/math/op_register/taichi_based.py
- brainpy/_src/math/tests/test_taichi_op_register.py
Implement taichi op register, but there's a problem to ensure the environment variable of taichi exist.
Still need to fix.
> [math] Implement taichi op register

- brainpy/_src/dyn/projections/conn.py
Fix a typo in error message which could be misleading.
Tests are not needed since it changes only the error message.
Documentation
- [ x ] Code follows the code style of this project.
- [ x ] Changes follow the **CONTRIBUTING** guidelines.
- [ x ] Update necessary documentation accordingly.
- [ x ] Lint and tests pass locally with the changes.
- [ x ] Check issues and pull requests first. You don't want to …
> Fix error message

- brainpy/_src/dyn/neurons/base.py
- brainpy/_src/dyn/neurons/lif.py
- brainpy/_src/math/ndarray.py
- brainpy/_src/math/op_register/base.py
- brainpy/_src/math/op_register/numba_based.py
- brainpy/_src/math/op_register/taichi_aot_based.py
- brainpy/_src/math/tests/test_ndarray.py
> [math] new abstract function for XLACustomOp, fix its bugs

- brainpy/_src/dynsys.py
- docs/_templates/ion_template.rst
- docs/apis/brainpy.dyn.channels.rst
- docs/apis/brainpy.dyn.ions.rst
> [doc] update doc

- brainpy/__init__.py
- brainpy/_src/dependency_check.py
- brainpy/_src/helpers.py
- brainpy/_src/math/object_transform/base.py
- brainpy/_src/math/op_register/tests/test_taichi_based.py
- brainpy/_src/math/scales.py
- docs/apis/brainpy.rst
- requirements-dev.txt
- requirements-doc.txt
> [dyn] add `save_state`, `load_state`, `reset_state`, and `clear_input` helpers

- brainpy/_src/delay.py
- brainpy/_src/dnn/linear.py
- brainpy/_src/dyn/projections/plasticity.py
- brainpy/_src/dyn/projections/tests/test_STDP.py
- brainpy/_src/math/jitconn/tests/test_event_matvec.py
- brainpy/_src/mixin.py
- docs/tutorial_toolbox/state_resetting.ipynb
- docs/tutorial_toolbox/state_saving_and_loading.ipynb
- setup.py
> [dyn] update STDP APIs on CPUs and fix bugs

- brainpy/initialize.py
Update initialize.py for proper TruncatedNormal importing
> add `TruncatedNormal` to `initialize.py`

- brainpy/_src/math/object_transform/base.py
upgrade variable retrieval, so that ``node.vars()`` on longer respect the class property
> [math] upgrade variable retrival

- requirements-doc.txt
> Update requirements-doc.txt to fix doc building temporally

- docs/tutorial_advanced/operator_custom_with_cupy.ipynb
Add Chinese version of `operator_custom_with_cupy.ipynb` and Rename it's title from "CPU and GPU Operator Customization with CuPy" to "GPU Operator Customization with CuPy".
> [doc] Add Chinese version of `operator_custom_with_cupy.ipynb` and Rename it's title

- brainpy/_src/math/object_transform/naming.py
- brainpy/_src/math/object_transform/tests/test_naming.py
- docs/tutorial_building/customize_dynamical_systems.ipynb
> fix the incorrect verbose of `clear_name_cache()`
