brainpy/BrainPy

.gitignore, README.rst, brainpy/connectivity/formatter.py, brainpy/connectivity/methods.py, brainpy/core_system/base.py, brainpy/core_system/synapses.py, brainpy/inputs.py, brainpy/measure.py, brainpy/tools/functions.py, docs/guides/how_it_works.rst, docs/guides/neurons.rst, docs/guides/numerical_integrators.rst, docs/guides/usage_of_connect_module.py, docs/guides/usage_of_connect_module.rst, docs/index.rst, docs/intro/build_network.ipynb, docs/intro/build_neurons.ipynb, docs/intro/build_synapses.ipynb, docs/intro/dynamics_analysis.ipynb, docs/intro/quick_start.ipynb, examples/networks/EI_balance_network.py, examples/networks/EI_net_for_fast_reponse.py, examples/networks/gamma_oscillation.py
- Add "integrators" attribute in NeuType/SynType
- Add EI network examples
- Fix Numba Dispatcher bug
- Update connectivity methods
=> More updates

.github/workflows/Linux_CI.yml, .github/workflows/MacOS_CI.yml, .github/workflows/Windows_CI.yml
add python 3.6 test on Linux and simplify macOS CI.
This PR is not stable, so this branch will continuously update until all bugs are fixed.
=> add py3.6 test & delete multiple macos env

setup.py
fix pip uninstall bugs by adding a backup function.
=> fix: update setup.py

brainpy/dyn/synapses/learning_rules.py
The original updating rules for ``I`` are erroneous. The second and third parameters in the ``bm.where()`` function should be reversed.
=> fix: fix the updating rules in the STP model

brainpy/math/autograd.py, brainpy/math/controls.py, brainpy/math/jit.py
Previously, errors occured in JIT function will change value contents of all variables. 
```python
>>> import brainpy.math as bm
>>>
>>> a = bm.Variable(bm.zeros(1))
>>> a = bm.zeros(1)
>>> @bm.jit
>>> def f():
>>>    a.value += 1
>>>    b.value += 1
>>> f()
brainpy.errors.MathError: JaxArray created outside of the jit function cannot be updated in JIT mode. You should mark it as brainpy.math.Variable instead.
>>> a
Variable(Traced<ShapedArray(float32[1])>with<DynamicJaxprTrace(level=0/1)>)
```
Now, the content will keep the same. For example, 
```python
>>> import brainpy.math as bm
>>>
>>> a = bm.Variable(bm.zeros(1))
>>> a = bm.zeros(1)
>>> @bm.jit
>>> def f():
>>>    a.value += 1
>>>    b.value += 1
>>> f()
brainpy.errors.MathError: JaxArray created outside of the jit function cannot …
```
=> JIT errors do not change Variable values

brainpy/dyn/base.py, brainpy/dyn/layers/dropout.py, brainpy/dyn/synapses/gap_junction.py, brainpy/math/jaxarray.py, brainpy/math/tests/test_jaxarray.py, examples/simulation/Fazli_2022_gj_coupled_bursting_pituitary_cells.py, extensions/brainpylib/atomic_sum.py, extensions/brainpylib/event_sum.py, extensions/brainpylib/utils.py, extensions/lib/event_sum_cpu.cc, extensions/lib/event_sum_gpu.cu, setup.py
This PR supports the initialization of a `Variable` by the data shape:
```python
>>> import brainpy.math as bm
>>> bm.Variable(10)
Variable([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)
```
=> Support initializing a Variable by data shape

docs/tutorial_advanced/compile_brainpylib.rst
Add compile_brainpylib documentation for users to build GPU wheel.
=> Docs: add compile_brainpylib documentation

extensions/setup_mac.py
Fixed setup mac script
`ext_modules = [
Pybind11Extension("brainpylib/cpu_ops",
sources=glob.glob("lib/cpu_*.cc"),
cxx_std=11,
extra_link_args=["-rpath", re.sub('/lib/.*', '/lib', sys.path[1])],
define_macros=[('VERSION_INFO', __version__)]),
]`
=> Fixed setup mac script

brainpy/connect/base.py, brainpy/connect/random_conn.py
- This modification mainly optimizes the connect time when using gpu and under "allow_multi_conn=True";
- Add connect rule "FixedTotalNum" under "allow_multi_conn=True" by default; 
- Use jax.numpy in "FixedProb,FixedPreNum,FixedPostNum" of the random_conn; 
- Use jax.numpy in "ij2csr" and add "ij2csr2" of the connect.base; 
- Distinguish between gpu and cpu using "ij2csr" and "ij2csr2" respectively;
- run Brette_2007_COBA.py to test;
=> optimizes the connect time when using gpu

brainpy/_src/dyn/base.py, brainpy/_src/dyn/runners.py, brainpy/_src/experimental/delay.py, brainpy/_src/experimental/neurons.py, brainpy/_src/experimental/synapses.py, brainpy/_src/experimental/synstp.py, brainpy/_src/math/__init__.py, brainpy/_src/math/activations.py, brainpy/_src/math/context.py, brainpy/_src/math/delayvars.py, brainpy/_src/math/environment.py, brainpy/_src/math/ndarray.py, brainpy/_src/train/back_propagation.py, brainpy/math/__init__.py, brainpy/math/activations.py, brainpy/math/context.py, brainpy/math/delayvars.py, brainpy/math/environment.py
``brainpy.math.share`` is designed to be a global context to communicate with all modules/nodes in a BrainPy program.
A snippet for its appilication:
```python
import brainpy as bp
import brainpy.math as bm
import brainpy.connect as C
from brainpy.math.context import share
class EINetv2(bp.DynamicalSystem):
def __init__(self, scale=1.0, e_input=20., i_input=20., delay=None):
super().__init__()
self.bg_exc = e_input
self.bg_inh = i_input
num_exc = int(3200 * scale)
num_inh = int(800 * scale)
pars = dict(V_rest=-60., V_th=-50., V_reset=-60., tau=20., tau_ref=5.,
V_initializer=bp.init.Normal(-55., 2.))
self.E = bp.experimental.LIF(num_exc, **pars)
self.I = bp.experimental.LIF(num_inh, **pars)
we = 0.6 / scale  # excitatory synaptic weight (voltage)
wi = 6.7 / scale  # inhibitory synaptic …
```
=> ``brainpy.math.share`` as the global context for sharing data across all modules/nodes

brainpy/_src/connect/base.py, brainpy/_src/connect/random_conn.py, brainpy/_src/connect/tests/test_GaussianProb_opt.py, requirements-dev.txt
Optimize GaussianProb with JAX and Create test_GaussianProb_opt.py to test its correction and optimization effect
Generate two connection matrix by calling `build_mat` function and change its `isOptimized` parameter to compare the results and time needed between before and after optimized
- CPU: Intel Core i5-1340P 8C16T(4P+8E)
- GPU: Intel® Iris® Xe Graphics eligible（No CUDA）
- RAM: 32G DDR4 3200MHz
- OS: Windows10 22H2
- Python: 3.10
============================= test session starts =============================
collecting ... collected 4 items
test_GaussianProb_opt.py::test_gaussian_prob1
test_GaussianProb_opt.py::test_gaussian_prob2
test_GaussianProb_opt.py::test_gaussian_prob3
test_GaussianProb_opt.py::test_gaussian_prob4
================== 4 passed, 1 warning in 134.70s (0:02:14) …
=> Optimize GaussianProb 

brainpy/_src/connect/base.py
The bug is on the line 428 of `connect/base.py`
```
elif COO in structures and not _has_coo_imp:
```
For the connectors of ScaleFreeBA, ScaleFreeBADual and PowerLaw, `build_mat` function has already implemented and there is no `build_coo` function, if we want to require `bp.connect.COO`, the judgment here is going to be correct and it's going to go down. So the logic here is wrong, just remove `not` is ok.
=> [fix] bug of `connect.base.py`'s `require` function

.github/workflows/CI.yml, brainpy/_src/dnn/tests/test_activation.py, brainpy/_src/dnn/tests/test_conv_layers.py, brainpy/_src/dnn/tests/test_function.py, brainpy/_src/dnn/tests/test_linear.py, brainpy/_src/dnn/tests/test_normalization.py, brainpy/_src/dnn/tests/test_pooling_layers.py
Add random.seed() before each test function
- Python 3.9
- Windows 10
- CPU: AMD Ryzen 7 4800H with Radeon Graphics
- GPU: NVIDIA GeForce RTX 2060
=> Add random.seed()

brainpy/_src/dnn/conv.py, brainpy/_src/dnn/function.py, brainpy/_src/dnn/nvar.py, brainpy/_src/dnn/pooling.py, brainpy/_src/dnn/rnncells.py, brainpy/_src/dnn/tests/test_mode.py, brainpy/_src/dnn/tests/test_rnncells.py
- OS: Windows 10
- Python: 3.9
- CPU: AMD Ryzen 7 4800H with Radeon Graphics
- GPU: NVIDIA GeForce RTX 2060
- Make Conv1d, Conv2d, Conv3d function support NonBatchingMode.
- Make ConvTranspose1d, ConvTranspose2d, ConvTranspose3d function support NonBatchingMode.
- Make Conv1dLSTMCell, Conv2dLSTMCell, Conv3dLSTMCell function support NonBatchingMode.
- Update and improve the tests.
=> Add NonBatchingMode function

brainpy/__init__.py, brainpy/_src/context.py, brainpy/_src/dyn/projections/aligns.py, brainpy/_src/dyn/rates/populations.py, brainpy/_src/integrators/sde/base.py, brainpy/_src/integrators/sde/normal.py, brainpy/_src/math/random.py, brainpy/_src/math/tests/test_random.py, examples/dynamics_simulation/decision_making_network.py, tests/simulation/test_net_rate_SL.py
Every time when calling ``brainpy.math.clear_buffer_memory()``, the random function in ``brainpy.math.random`` will not be available except when recalling ``brainpy.math.random.seed()``. 
This PR fixes this problem and every time after the ``clear_buffer_memory`` is called, the random key of ``brainpy.math.random.DEFAULT`` will be regenerated automatically.
=> Creat random key automatically when it is detected

brainpy/_src/checkpoints/io.py, brainpy/_src/checkpoints/tests/test_io.py, brainpy/_src/connect/random_conn.py, brainpy/_src/dyn/neurons/hh.py, brainpy/_src/dyn/projections/aligns.py, brainpy/_src/math/modes.py, brainpy/_src/math/object_transform/base.py, brainpy/_src/math/object_transform/tests/test_variable.py, brainpy/_src/math/object_transform/variables.py, brainpy/_src/math/random.py, brainpy/_src/math/sparse/_csr_mv.py, brainpy/_src/running/pathos_multiprocessing.py, brainpy/math/random.py, examples/dynamics_simulation/COBA_parallel.py, requirements-dev.txt, requirements-doc.txt, requirements.txt
Flax and other libraries support object-oriented (OO) programming by providing variable tracing during computation and transformations. On the contrary, BrainPy is designed to be Pythonic, and its OO interface supports tracing variables before transformations. Now, we are excited that BrainPy also supports tracing variables during transformations. 
Particularly, we provide `.tracing_variable()`. 
Here is the usage example::
```python
class Example(bm.BrainPyObject):
def fun(self):
self.tracing_variable('a', bm.zeros, (10,))
self.a.value = bm.ones(10)
a = self.tracing_variable('a', bm.zeros, (10,))
```
=> Support tracing ``Variable`` during computation and compilation by using ``tracing_variable()`` function

docs/quickstart/installation.rst
=> [docs] Update installation.rst

.github/workflows/docker.yml, README.md, docker/Dockerfile, docker/requirements.txt, docs/quickstart/installation.rst
- Add CPU-version BrainPy dockers with amd64 and arm64 support. 
- Add corresponding docs.
=> [docs] add BrainPy docker and docs

brainpy/_src/math/object_transform/autograd.py, brainpy/_src/math/op_registers/tests/test_ei_net.py, requirements-dev.txt, requirements-doc.txt, requirements.txt, setup.py
- avoid of using ``jax>=0.4.16`
=> [bug] fix compatible bug

brainpy/_src/delay.py, brainpy/_src/dyn/projections/aligns.py, brainpy/_src/dyn/projections/plasticity.py, brainpy/_src/dyn/projections/tests/test_aligns.py, brainpy/_src/dynsys.py, brainpy/_src/math/modes.py, brainpy/_src/math/object_transform/autograd.py, brainpy/_src/math/object_transform/base.py, brainpy/_src/math/random.py, brainpy/_src/mixin.py, brainpy/_src/tests/test_mixin.py, brainpy/dyn/neurons.py, brainpy/initialize.py, brainpy/mixin.py, docs/apis/initialize.rst
Plasticity models and projection methods are reorganized.
All passed.
=> [projection] upgrade projections so that APIs are reused across different models

brainpy/_src/math/brainpylib_check.py, brainpy/_src/math/op_register/taichi_aot_based.py, brainpy/_src/tools/package.py, requirements.txt
=> [math] remove the hard requirement of `taichi`

brainpy/_src/dyn/neurons/base.py, brainpy/_src/dyn/neurons/lif.py, brainpy/_src/math/ndarray.py, brainpy/_src/math/tests/test_ndarray.py
=> [math] fix numpy array priority

docs/core_concept/brainpy_dynamical_system.ipynb
Fix typo in `docs/core_concept/brainpy_dynamical_system.ipynb`
=> [docs] Fix typo in docs

brainpy/_src/dynold/neurons/reduced_models.py, brainpy/_src/math/interoperability.py, brainpy/_src/math/surrogate/__init__.py, brainpy/_src/math/surrogate/_one_input_new.py, brainpy/_src/mixin.py, brainpy/math/interoperability.py, brainpy/math/surrogate.py
- add ``heaviside_p`` primitive
- all surrogate functions (with one argument) support both JVP (forward) and VJP (backward) differentiations
- enabling the forward gradients of spiking neural networks
Yes.
=> [math] change the internal implementation of surrogate function

brainpy/_src/losses/comparison.py, brainpy/losses.py
add support for multi-class margin loss
=> add support for multi-class margin loss

brainpy/_src/dyn/synapses/abstract_models.py, brainpy/_src/dynold/synapses/abstract_models.py
=> [Dyn] Fix alpha synapse bugs

brainpy/_src/initialize/random_inits.py
=> Fix `_format_shape` in `random_inits.py`

brainpy/_src/dynsys.py
The warning can only occur when the top-most model's ``reset_state`` is used.
=> [dyn] fix warning of reset_state

brainpy/_src/math/event/tests/event_csrmv_taichi_VS_event_csrmv.py, brainpy/_src/math/event/tests/event_csrmv_taichi_VS_event_csrmv_grad.py, brainpy/_src/math/jitconn/tests/jitconn_event_matvec_taichi_VS_jitconn_event_matvec.py, brainpy/_src/math/jitconn/tests/jitconn_event_matvec_taichi_VS_jitconn_event_matvec_grad.py, brainpy/_src/math/jitconn/tests/jitconn_matvec_taichi_VS_jitconn_matvec.py, brainpy/_src/math/jitconn/tests/jitconn_matvec_taichi_VS_jitconn_matvec_grad.py, brainpy/_src/math/op_register/taichi_aot_based.py, brainpy/_src/math/sparse/_csr_mv_taichi.py, brainpy/_src/math/sparse/tests/csrmv_taichi_VS_csrmv.py, brainpy/_src/math/sparse/tests/csrmv_taichi_VS_csrmv_grad.py
Support taichi customized op with metal cpu backend
=> [math] Support taichi customized op with metal cpu backend

brainpy/_src/math/op_register/__init__.py, brainpy/_src/math/op_register/base.py, brainpy/_src/math/op_register/taichi_aot_based.py, brainpy/_src/math/op_register/tests/test_taichi_clean_cache.py, brainpy/math/op_register.py, docs/tutorial_advanced/operator_custom_with_taichi.ipynb
Make taichi caches more transparent and Add clean caches function
=> [taichi] Make taichi caches more transparent and Add clean caches function

brainpy/_src/dynsys.py
Usually, we use `step_run` with `brainpy.math.for_loop`. This function does not call `brainpy.clear_input`, which may cause problems of input accumulation when using old APIs in ``brainpy.neurons`` module. Therefore, we should call ``brainpy.clear_input`` after each ``update`` function.
=> [dyn] add `clear_input` in the `step_run` function.

.github/workflows/CI.yml
> This is an effect of a change introduced with pytest 5.0.0. From the release notes:
>
> > \#5440: The faulthandler standard library module is now enabled by default to help users diagnose crashes in C modules.
> >
> > This functionality was provided by integrating the external pytest-faulthandler plugin into the core, so users should remove that plugin from their requirements if used.
> >
> > For more information see the docs: https://docs.pytest.org/en/stable/usage.html#fault-handler
>
> You can mute these errors as follows:
>
> ```py
> pytest -p no:faulthandler
> ```
=> [ci] Fix windows pytest fatal exception

brainpy/__init__.py, brainpy/_src/delay.py, brainpy/_src/dynold/synapses/abstract_models.py, brainpy/_src/dynold/synapses/base.py, brainpy/_src/dynsys.py, brainpy/_src/math/object_transform/base.py, brainpy/_src/tests/test_base_classes.py, brainpy/_src/tests/test_delay.py, brainpy/_src/tests/test_mixin.py
- Fix ``VarDelay`` bugs
- Fix `DynamicalSystem.register_local_delay()` bugs
=> Fix delay bug

brainpy/_src/analysis/highdim/slow_points.py, brainpy/_src/dyn/rates/tests/test_nvar.py, brainpy/_src/initialize/tests/test_decay_inits.py, brainpy/_src/integrators/ode/tests/test_ode_method_exp_euler.py, brainpy/_src/integrators/runner.py, brainpy/_src/math/ndarray.py, brainpy/_src/math/object_transform/controls.py, brainpy/_src/math/object_transform/jit.py, brainpy/_src/math/object_transform/tests/test_autograd.py, brainpy/_src/math/object_transform/tests/test_base.py, brainpy/_src/math/object_transform/tests/test_circular_reference.py, brainpy/_src/math/object_transform/tests/test_collector.py, brainpy/_src/math/object_transform/tests/test_controls.py, brainpy/_src/math/object_transform/tests/test_jit.py, brainpy/_src/math/random.py, brainpy/_src/optimizers/tests/test_ModifyLr.py, brainpy/_src/runners.py, brainpy/_src/train/offline.py, brainpy/_src/train/online.py, brainpy/check.py, requirements-dev.txt
Because of the deprecation of from jax.experimental.host_callback import id_tap, replace jax.experimental.host_callback with jax.pure_callback.
Also support jax==0.4.28:
> The kind argument to jax.numpy.sort and jax.numpy.argsort is now removed. Use stable=True or stable=False instead.
=> [fix] Replace jax.experimental.host_callback with jax.pure_callback

brainpy/_src/dependency_check.py, brainpy/_src/math/op_register/__init__.py, brainpy/_src/math/op_register/numba_approach/__init__.py, brainpy/_src/math/op_register/tests/test_numba_based.py, requirements-dev.txt
Update `CustomOpByNumba` to support JAX version >= 0.4.24 by implementing mlir register rules
=> [math] Update `CustomOpByNumba` to support JAX version >= 0.4.24

brainpy/_src/dnn/linear.py, brainpy/_src/math/jitconn/matvec.py, brainpy/_src/math/jitconn/tests/test_get_conn_matrix.py, brainpy/_src/math/jitconn/tests/test_get_connect_matrix.py, brainpy/_src/math/op_register/base.py, brainpy/math/jitconn.py
Add getting JIT connect matrix method `brainpy.math.jitconn.get_connect_matrix` for getting the dense connect matrix in the procedure of jitconn opeartors.
Add function `get_connect_matrix` for `JitFPHomoLinear`, `JitFPUniformLinear`, `JitFPNormalLinear`, `EventJitFPHomoLinear`, `EventJitFPUniformLinear` and `EventJitFPNormalLinear` in the module `brainpy.dnn.linear`
=> [math] Add getting JIT connect matrix method for `brainpy.dnn.linear`

brainpy/_src/dynsys.py
#676 
`collections.Iterable` is deprecated. Replace it with `collections.abc.Iterable`.
=> [bug] Replace `collections.Iterable` with `collections.abc.Iterable`

brainpy/_src/integrators/runner.py, brainpy/_src/math/object_transform/controls.py, brainpy/_src/math/random.py, brainpy/_src/runners.py, brainpy/_src/train/offline.py, brainpy/_src/train/online.py
`jax.pure_callback()` may not work as expected for certain use cases, such as updating a progress bar, whereas `jax.debug.callback()`can be used effectively.
`jax.pure_callback()` is intended for pure functions without side effects. If JAX determines that the callback's result isn't used in the computation, it might optimize the callback call out, which means updates to a progress bar (a side effect) wouldn't occur.
`jax.debug.callback()`, on the other hand, does not assume the function is pure and always executes the callback as part of the computation. This consistency ensures that progress bar updates and other side effects happen reliably, even under JAX transformations like jit and vmap.
For more detail, see https://jax.readthedocs.io/en/latest/notebooks/external_callbacks.html
=> [bug] Fix prograss bar is not displayed and updated as expected

.github/workflows/CI.yml, README.md, brainpy/_src/dnn/tests/test_activation.py, brainpy/_src/dnn/tests/test_conv_layers.py, brainpy/_src/math/op_register/ad_support.py
This pull request includes an update to the `README.md` file to introduce and describe the Brain Dynamics Programming (BDP) ecosystem. The most important changes include adding a new section about the BDP ecosystem, providing a link to further details, and inviting community contributions.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R52-R64): Added a new section titled "Brain Dynamics Programming Ecosystem" that describes the BDP ecosystem, its modular design, and provides a link for more information. Additionally, it invites contributions from the community and provides a contact email.
=> [readme] Update README.md

docs/index.rst, setup.py
This pull request includes changes to the installation instructions and dependencies for the `brainpy` package, specifically removing support for CUDA 11 and updating the documentation accordingly.
Updates to installation instructions and dependencies:
* [`docs/index.rst`](diffhunk://#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534L23-R23): Removed the installation instructions for GPU with CUDA 11 and updated the tab label for CUDA 12.
* [`setup.py`](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L71-L76): Removed the dependencies for CUDA 11 and adjusted the extras_require section to reflect this change.
=> [dependency] Remove unnecessary dependency

brainpy/_src/dnn/linear.py, docker/requirements.txt, docs/quickstart/installation.rst
This pull request includes several updates to the `brainpy` library, focusing on dependency management and error handling improvements. The most important changes involve adding a new dependency, refining error handling for missing packages, and updating documentation to reflect these changes.
Closes #702
* Added `braintaichi` to the list of dependencies in `docker/requirements.txt`.
* Replaced `PackageMissingError` with `raise_braintaichi_not_found()` in multiple functions to provide a more specific error message when `braintaichi` is not found in `brainpy/_src/dnn/linear.py`. [[1]](diffhunk://#diff-77f7b5741aa049070a3ddbcb76c626e7e0e239b6602e1a80c41ccaf60598f93bL324-R324) [[2]](diffhunk://#diff-77f7b5741aa049070a3ddbcb76c626e7e0e239b6602e1a80c41ccaf60598f93bL344-R344) …
=> [dnn] Improve error handling in `dnn/linear` module

.github/workflows/CI-models.yml, .github/workflows/CI.yml, requirements-dev.txt
This pull request includes updates to the CI configuration files to add support for Python 3.12. The changes are made across multiple sections in two files: `.github/workflows/CI-models.yml` and `.github/workflows/CI.yml`.
Updates to CI configuration:
* [`.github/workflows/CI-models.yml`](diffhunk://#diff-92c106692b8ac80629dc2acd22fdc0ac5f445000eb97458e2b88b85b0a342833L25-R25): Added Python 3.12 to the `python-version` matrix in three different job strategies. [[1]](diffhunk://#diff-92c106692b8ac80629dc2acd22fdc0ac5f445000eb97458e2b88b85b0a342833L25-R25) [[2]](diffhunk://#diff-92c106692b8ac80629dc2acd22fdc0ac5f445000eb97458e2b88b85b0a342833L73-R73) [[3]](diffhunk://#diff-92c106692b8ac80629dc2acd22fdc0ac5f445000eb97458e2b88b85b0a342833L122-R122)
* …
=> [ci] Add ci support for python 3.12

brainpy/_src/math/ndarray.py, brainpy/_src/math/tests/test_ndarray.py
This pull request includes a small change to the `brainpy/_src/math/tests/test_ndarray.py` file. The change updates the exception type in the `test_tracing` method to correctly handle the expected error.
* [`brainpy/_src/math/tests/test_ndarray.py`](diffhunk://#diff-c7f1382a5fd6138f459104856edbe92c2b222909940d9742afcfaab379ccc999L65-R65): Updated the exception type from `RuntimeError` to `jax.errors.UnexpectedTracerError` in the `test_tracing` method.
=> [ci] Fix bug in `test_ndarray.py` when using the latest version of JAX

brainpy/_src/dependency_check.py
This pull request simplifies error handling in the `import_braintaichi` function by removing an unnecessary helper function and directly raising the caught exception. 
Error handling improvements:
* [`brainpy/_src/dependency_check.py`](diffhunk://#diff-2165e9fbe8ca8446179163054210b26cc98aeae80f6c6063d91ce0fa0ffc7f11L55-L66): Removed the `raise_braintaichi_not_found` helper function and updated the `import_braintaichi` function to raise the caught `ModuleNotFoundError` directly with its original context. This change ensures that the original exception details are preserved for better debugging.
=> [bug] Fix exception handling for missing braintaichi module in dependency check

.github/workflows/CI-models.yml, .github/workflows/CI.yml, brainpy/_src/math/object_transform/base.py, setup.py
Closes #748 
This pull request includes a minor but important change to the `__load_state__` method in the `brainpy/_src/math/object_transform/base.py` file. The change swaps the order of the returned values, ensuring `missing_keys` is returned before `unexpected_keys`.
* [`brainpy/_src/math/object_transform/base.py`](diffhunk://#diff-04cd59832a1e69d7e6c69b966d046f4ea4251848a96abf7788b4e27a01f0287bL520-R520): Updated the `__load_state__` method to return `missing_keys` first, followed by `unexpected_keys`, aligning with expected conventions or use cases.
=> [bug] Fix order of return values in `__load_state__`

README.md, brainpy/_src/analysis/lowdim/lowdim_analyzer.py, brainpy/_src/analysis/lowdim/lowdim_bifurcation.py, brainpy/_src/connect/random_conn.py, docs/index.rst, setup.py
This pull request includes updates to the documentation, codebase, and dependency management for the BrainPy project. The changes focus on improving clarity, updating installation instructions, and ensuring consistency with the project's recent rewrite based on the BrainState framework.
* Updated the license badge in `README.md` to use a GNU GPLv3 badge and removed references to OpenI. Added a note about BrainPy's rewrite based on BrainState and updated the Python version requirement to 3.10. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L9-R30) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R64)
* Simplified installation instructions in `docs/index.rst` by removing dependency links for GPU and TPU …
=> [update] Refine installation instructions and improve docstring formatting
